services:
  web:
    build: .
    ports:
      - "8080:80"
    restart: always
    environment:
      ConnectionStrings__AppDbContext: "Server=192.168.1.33,1433;Database=WebProjesi;User Id=sa;Password=1;TrustServerCertificate=True;"
