// <auto-generated />
namespace CodeBud.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class AddPermissionTablesToContext : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddPermissionTablesToContext));
        
        string IMigrationMetadata.Id
        {
            get { return "202505251740137_AddPermissionTablesToContext"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
